# Generated by Django 3.2.7 on 2021-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=64)),
                ('semestry', models.CharField(choices=[(1, '1'), (2, '2')], default=1, max_length=5)),
                ('year', models.PositiveIntegerField()),
                ('vacancy', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='CLOSE', max_length=5)),
            ],
        ),
    ]
