# Generated by Django 3.2.7 on 2021-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.PositiveIntegerField(max_length=10)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='courses.Course')),
            ],
        ),
    ]
