# Generated by Django 3.2.7 on 2021-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_student_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semestry',
            field=models.CharField(choices=[('1', '1'), ('1', '2')], default='', max_length=5),
        ),
    ]
